# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PROJECT_Example' do
    pod 'CCAlertView', :path => '../'
    target 'PROJECT_Tests' do
        inherit! :search_paths
    end
end
